apiVersion: apps/v1
kind: Deployment

metadata:
  name: booking-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: booking-app

  template:
    metadata:
      labels:
        app: booking-app

    spec:
      containers:
        - name: booking-app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: 8000

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: booking-config
                  key: APP_ENV

            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: booking-config
                  key: APP_NAME

            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: booking-config
                  key: LOG_LEVEL

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: DATABASE_URL
